---
- name: clone nvm.git
  become: yes
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{nvm_root}}"

- name: make group of nvm
  become: yes
  group: name=nvm

- name: change attributes of {{nvm_root}}
  become: yes
  file:
    path: "{{nvm_root}}"
    mode: g+rwXs
    group: nvm
    state: directory
    recurse: yes

- name: set node.js env file
  become: yes
  template: src=nvm.sh.j2 dest=/etc/profile.d/nvm.sh
