---
- name: add user
  become: yes
  user:
    name: "{{user}}"
    password: "$6$rounds=656000$AT3KtKdnzx9iJ00F$qoGzOkIzEVw0tjwMdcg1B0HyLGr6a8Jvxu5VTUGweqXkEsLiK8RFRdxRTRlFWTJksqTZDRfCbqs7pofS7FxQH1"
    shell: /bin/bash
