---
- name: install ctags in RedHat family
  become: yes
  yum: name=ctags state=latest
  when: ansible_os_family == 'RedHat'

- name: install ctags in Debian family
  become: yes
  apt: name=ctags state=latest
  when: ansible_os_family == 'Debian'



