---
- name: install zsh in RedHat family
  become: yes
  yum: name=zsh state=latest
  when: ansible_os_family == 'RedHat'

- name: install zsh in Debian family
  become: yes
  apt: name=zsh state=latest
  when: ansible_os_family == 'Debian'
