- name: add repository for ffmpeg
  become: yes
  apt_repository: >
    repo='ppa:mc3man/trusty-media'
    update_cache=yes
    state=present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'

- name: install ffmpeg
  become: yes
  apt: name=ffmpeg state=latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'
