---
version: 2.8.21
download_url: https://github.com/antirez/redis/archive/{{ version }}.tar.gz
download_dest: /tmp
downloaded_file: "{{ download_dest }}/redis-{{ version }}.tar.gz"
source_dir: /tmp/redis-{{ version }}
port: 6379
conf_file: /etc/redis/{{ port }}.conf
pid_file: /var/run/redis_{{ port }}.pid
log_file: /var/log/redis_{{ port }}.log
redis_dir: /var/redis/{{ port }}
