---
- name: install mysql
  become: yes
  yum: name={{item}} state=latest
  with_items:
    - mysql
    - mysql-devel
    - mysql-server
    - mysql-utilities

- name: service mysql
  become: yes
  service:
    name: mysqld
    state: started
    enabled: yes
