---
- name: install tmux in RedHat family
  become: yes
  yum: name=tmux state=latest
  when: ansible_os_family == 'RedHat'

- name: install tmux in Debian family
  become: yes
  apt: name=tmux state=latest
  when: ansible_os_family == 'Debian'
