---
- name: install build-essential
  become: yes
  apt: name=build-essential state=latest

- name: install dependencies
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - gettext
    - libncurses5-dev
    - libacl1-dev
    - libgpm-dev
    - python-dev
    - python3-dev
    - ruby-dev
    - lua5.2
    - liblua5.2-dev
    - luajit
    - libluajit-5.1-2

- name: clone vim repositry from github
  become: yes
  git: >
    repo=https://github.com/vim/vim.git
    dest={{src_dir}}
    force=yes

- name: configure vim source
  become: yes
  shell: >
    ./configure
    --with-features=huge
    --enable-multibyte
    --enable-luainterp
    --enable-luajit
    --enable-rubyinterp
    --enable-pythoninterp
    --enable-python3interp
    --enable-fail-if-missing
  args:
    chdir: "{{src_dir}}"

- name: compile vim source
  become: yes
  shell: make
  args:
    chdir: "{{src_dir}}"

- name: install vim files
  become: yes
  shell: make install
  args:
    chdir: "{{src_dir}}"
