---
- name: install build-essential
  become: yes
  apt: name=build-essential state=latest

- name: install dependencies
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - ncurses-dev
    - libtolua-dev
    - python-dev
    - ruby-dev

- name: clone vim repositry from github
  become: yes
  git: >
    repo=https://github.com/vim/vim.git
    dest={{src_dir}}
    force=yes

- name: configure vim source
  become: yes
  shell: >
    ./configure
    --with-features=huge
    --enable-multibyte
    --enable-luainterp
    --enable-rubyinterp
    --enable-pythoninterp
  args:
    chdir: "{{src_dir}}"

- name: compile vim source
  become: yes
  shell: make
  args:
    chdir: "{{src_dir}}"

- name: install vim files
  become: yes
  shell: make install
  args:
    chdir: "{{src_dir}}"
