---
- name: install dependencies in CentOS
  sudo: yes
  yum: name={{item}} state=latest
  with_items:
    - gcc
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
  when: ansible_distribution == 'CentOS'

- name: install dependencies in Debian family
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
  when: ansible_os_family == 'Debian'

- name: install rbenv
  sudo: yes
  git: repo=https://github.com/sstephenson/rbenv.git dest={{rbenv_root}}

- name: install ruby-build
  sudo: yes
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{rbenv_root}}/plugins/ruby-build

- name: make rbenv group
  sudo: yes
  group: name=rbenv

- name: set rbenv env file
  sudo: yes
  template: >
    src=rbenv.sh.j2
    dest=/etc/profile.d/rbenv.sh
    mode=664
    group=rbenv

- name: change attributes of {{rbenv_root}}
  sudo: yes
  file:
    path: "{{rbenv_root}}"
    mode: g+rwXs
    group: rbenv
    state: directory
    recurse: yes

- name: add user to rbenv group
  sudo: yes
  user: name={{rbenv_user}} append=yes groups=rbenv

- name: check whether ruby was already installed or not
  shell: /bin/bash -lc 'rbenv global {{ruby_version}}'
  ignore_errors: yes
  register: result

- name: install ruby with rbenv
  shell: /bin/bash -lc 'rbenv install {{ruby_version}}'
  when: result|failed

- name: set ruby {{ruby_version}} for system
  shell: /bin/bash -lc 'rbenv global {{ruby_version}} && rbenv rehash'
  when: result|failed

- name: install gem pry
  command: /bin/bash -lc 'gem install pry'
  when: result|failed

- name: install gem bundler
  command: /bin/bash -lc 'gem install bundler'
  when: result|failed
