---
- name: install dependencies
  sudo: yes
  yum: name={{item}} state=latest
  with_items:
    - openssl-devel
    - readline-devel
    - zlib-devel

- name: install rbenv
  sudo: yes
  git: repo=https://github.com/sstephenson/rbenv.git dest={{rbenv_root}} force=yes

- name: install ruby-build
  sudo: yes
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{rbenv_root}}/plugins/ruby-build force=yes

- name: set rbenv env file
  sudo: yes
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh

- name: make rbenv group
  sudo: yes
  group: name=rbenv

- name: change attributes of {{rbenv_root}}
  sudo: yes
  file:
    path: "{{rbenv_root}}"
    mode: g+rwXs
    group: rbenv
    state: directory
    recurse: yes

- name: add user to rbenv group
  sudo: yes
  user: name={{rbenv_user}} append=yes groups=rbenv

- name: install ruby with rbenv
  shell: /bin/bash -lc 'rbenv install {{ruby_version}}'

- name: set ruby {{ruby_version}} for system
  shell: /bin/bash -lc 'rbenv global {{ruby_version}} && rbenv rehash'
